config/routes.rb
FEDCIM::Application.routes.draw do

  get 'cotizaciones/update_detalle', to: 'cotizaciones#update_detalle'
  
  resources :detalles

  resources :servicios

  get "stats" => "stats#index", :as => "stats"

  resources :documentos

  resources :municipios do
    get :autocomplete_departamento_nombre, :on => :collection
  end 

  resources :departamentos

  get "logout" => "sessions#destroy", :as => "logout"
  get "login"  => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get "pages/home"

  get 'cotizaciones/cal_cost', to: 'cotizaciones#cal_cost'
  get 'cotizaciones/cal_costp', to: 'cotizaciones#cal_costp'
  get 'cotizaciones/total_cost', to: 'cotizaciones#total_cost'

  resources :users

  resources :sessions

  resources :cotizaciones

  resources :patronajes_basicos
  resources :clientes do 
    get :autocomplete_municipio_nombre, :on => :collection  
  end
  
  resources :contactos

  root :to => 'pages#home'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new # guest user(not logged in)
    if user.has_role? :admin
        can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  belongs_to :municipio
  attr_accessible :nombres, :apellidos, :cedula, :empresa, :nit
  attr_accessible :cargo, :telefono, :direccion, :celular, :fax, :email, :municipio_id
  attr_accessible :municipio_nombre

  def municipio_nombre
    municipio.nombre if municipio
  end

  def municipio_nombre=(nombre)
  	self.municipio  = Municipio.find_or_create_by_nombre(nombre) unless nombre.blank? 
  end

end

app/models/contacto.rb
class Contacto < ActiveRecord::Base
  attr_accessible :apellido, :celular, :email, :nombre, :telefono, :created_at, :mes

    def self.splfecm(fecha)
	    fecstr = fecha.to_s 
	  	splife = fecstr.split("-")
	  	@fec = splife[1]
	  	@fec.to_i
	end

	def self.splfecd(fecha)
	    fecstr = fecha.to_s 
	  	splife = fecstr.split("-")
	  	@fec = splife[2]
	  	@fec.to_i
	end

	def self.splfeca(fecha)
	    fecstr = fecha.to_s 
	  	splife = fecstr.split("-")
	  	@fec = splife[0]
	  	@fec.to_i
	end

end

app/models/cotizacion.rb
class Cotizacion < ActiveRecord::Base
  belongs_to :servicio
  belongs_to :detalle
  attr_accessible :precio, :total, :servicio_id, :detalle_id
end

app/models/departamento.rb
class Departamento < ActiveRecord::Base
  has_many :municipios
  attr_accessible :nombre, :sigla
end

app/models/detalle.rb
class Detalle < ActiveRecord::Base
  belongs_to :servicio
  attr_accessible :pieza, :precio, :servicio_id
end

app/models/documento.rb
class Documento < ActiveRecord::Base
  # attr_accessible :title, :body
  #paperclip
  attr_accessible :precios
  has_attached_file :precios,
  :url  => "/assets/documentos/:id/:style/:basename.:extension",
  :path => ":rails_root/public/assets/documentos/:id/:style/:basename.:extension"

  validates_attachment_presence :precios
  #validates_attachment_size :foto, :less_than => 5.megabytes
  validates_attachment_content_type :precios, :content_type => ['application/pdf'],
  :message => "solo se permiten pdf"
end

app/models/municipio.rb
class Municipio < ActiveRecord::Base
  belongs_to :departamento
  attr_accessible :nombre, :sigla, :departamento_id, :departamento_nombre

  def departamento_nombre
  	departamento.nombre if departamento
  end

  def departamento_nombre=(nombre)
  	self.departamento  = Departamento.find_or_create_by_nombre(nombre) unless nombre.blank? 
  end

  def self.muni_ubica(muni)
  	@ubica = muni.nombre + ' | ' + muni.departamento.nombre
  end

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify

  #has_and_belongs_to_many :users
  #belongs_to :resource, :polymorphic => true

  def self.act
  		role = Role.all
  end
end

app/models/servicio.rb
class Servicio < ActiveRecord::Base
  has_many :cotizaciones
  has_many :detalles	
  attr_accessible :nombre
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  authenticates_with_sorcery!
  attr_accessible :username,:email, :password, :salt 
  attr_accessible :password_confirmation
  attr_accessible :created_at, :updated_at, :remember_me_token, :remember_me_token_expires_at 


  validates_presence_of :password_confirmation
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  validates_presence_of :username
  validates_uniqueness_of :username
end
  

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  load_and_authorize_resource :only => [:new, :edit, :destroy]
  autocomplete :municipio, :nombre, :full => true

  def index
    @clientes = Cliente.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clientes }
    end
  end

  def show
    @cliente = Cliente.find(params[:id])
  end

  def new
    @cliente = Cliente.new
  end

  def edit
    @cliente = Cliente.find(params[:id])
  end

  def create
    @cliente = Cliente.new(params[:cliente])
    render :action => :new unless @cliente.save
  end

  def update
    @cliente = Cliente.find(params[:id])
    render :action  => :edit unless @cliente.update_attributes(params[:cliente])
  end

  def destroy
    @cliente = Cliente.find(params[:id])
    @cliente.destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/contactos_helper.rb
module ContactosHelper
end

app/helpers/detalles_helper.rb
module DetallesHelper
end

app/helpers/documentos_helper.rb
module DocumentosHelper
end

app/helpers/municipios_helper.rb
module MunicipiosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/servicios_helper.rb
module ServiciosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stats_helper.rb
 module StatsHelper
 
	def stat_for_contactos
		@numcon = Contacto.count(:group => :mes)

		leyenda = []         # leyendas del grafico

		@numcon.collect do |key, value| 
			case key
			when 1
			  leyenda << "Enero #{value} Contactos"
			when 2
			  leyenda << "Febrero #{value} Contactos"
			when 3
			  leyenda << "Marzo #{value} Contactos"
			when 4
			  leyenda << "Abril  #{value} Contactos"
			when 5
			  leyenda << "Mayo #{value} Contactos"
			when 6
			  leyenda << "Junio #{value} Contactos"
			when 7
			  leyenda << "Julio #{value} Contactos"
			when 8
			  leyenda << "Agosto #{value} Contactos"
		    when 9
			  leyenda << "Septiembre #{value} Contactos"
			when 10
			  leyenda << "Octubre #{value} Contactos"
			when 11
			  leyenda << "Noviembre #{value} Contactos"
			when 12
			  leyenda << "Diciembre #{value} Contactos"
			when nil
			  leyenda << "No Hay Valoracion"
			end
		end

		Gchart.pie(
	    :size => '695x380',
	    :theme => :keynote,
	    :title => "Contactos por Mes", 
	    :bg => 'efefef',
	    :labels => leyenda,
	    :data => @numcon.values,
	    :axis_with_labels => 'x,y',
	    :axis_labels =>  [@numcon.values])
	    
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/clientes/_cliente.html.erb
<tr id=<%= "cliente_#{cliente.id}" %>>
	
	<td><%= cliente.nombres %></td>
    <td><%= cliente.apellidos %></td>
    <td><%= cliente.cedula %></td>
    <td><%= cliente.empresa %></td>
    <td><%= cliente.nit %></td>
    <td><%= cliente.cargo %></td>
    <td><%= cliente.telefono %></td>
    <td><%= cliente.direccion %></td>
    <td><%= cliente.celular %></td>
    <td><%= cliente.fax %></td>
    <td><%= cliente.email %></td>
    <td><%= cliente.municipio.nombre %></td>

	<td>
        <div class="btn-group">
            <a class="btn btn-mini dropdown-toggle btn-success" data-toggle="dropdown" href="#"><span class="caret"></span>Action
            
            </a>
            <ul class="dropdown-menu anchmenu">
           
                <p><%= link_to 'Mostrar', cliente, :remote => true, :class => 'btn btn-mini btn-success' %></p>
                <p><%= link_to 'Editar', edit_cliente_path(cliente), :remote => true, :class => 'btn btn-mini' %></p>
                <p><%= link_to 'Eliminar', cliente,  :data => { :confirm => 'Esta Seguro?' }, :method => :delete, :remote => true, :class => 'btn btn-mini btn-danger' %></p>
            </ul>
      </div>
	</td>
</tr>

app/views/clientes/_form.html.erb
<%= simple_form_for(@cliente, :html => { :class => 'form-horizontal' }, :remote => true) do |f| %>

  <div class="modal-body">
    <div class="control-group span10">
      <div class="row">
        <div class="span5">
          <%= f.input :nombres %>
          <%= f.input :apellidos %>
          <%= f.input :cedula %>
          <%= f.input :empresa %>
          <%= f.input :nit %>
          <%= f.input :cargo %>
        </div>

        <div class="span2">
          <div class="row">
            <%= f.input :telefono %>
            <%= f.input :direccion %>
            <%= f.input :celular %>
            <%= f.input :fax %>
            <%= f.input :email %>
            <%= f.input :municipio_nombre, :url => autocomplete_municipio_nombre_clientes_path, :as => :autocomplete, :id_element => '#id'%>
          </div>
        </div>
      </div>
    </div>
    <%= f.button :submit, :class => 'btn-primary btn-success' %>
    <%= link_to "cancelar", clientes_path, :class => 'btn btn-success' %>
  </div>  
<% end %>

app/views/clientes/_show.html.erb
<%- model_class = Cliente -%>
<div class="page-header">

  <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true" onclick="$.lazybox.close()">&times;</button>
      <h1>Cliente:<%= @cliente.nombres %></h1>
   </div>
  
</div>


<div class="row">

  <div class="span2">
    <p><%= @cliente.nombres %></p>
    <p><%= @cliente.apellidos %></p>
    <p><%= @cliente.cedula %></p>
    <p><%= @cliente.empresa %></p>
    <p><%= @cliente.nit %></p>
    <p><%= @cliente.cargo %></p>
  </div>
  <div class="span2">
      <div class="row">
        <p><%= @cliente.telefono %></p>
        <p><%= @cliente.direccion %></p>
        <p><%= @cliente.celular %></p>
        <p><%= @cliente.fax %></p>
        <p><%= @cliente.email %></p>
        <p><%= @cliente.municipio.nombre %></p>
       
      </div>
  </div>    
</div> 

app/views/clientes/create.js.erb
$('table tbody').append("<%= escape_javascript(render @cliente) %>")
$.lazybox.close()

app/views/clientes/destroy.js.erb
$("table tr#cliente_<%= @cliente.id %>").remove();

app/views/clientes/edit.js.erb
$.lazybox("<%= j(render :partial => 'form') %>", {niceClose: true});

app/views/clientes/index.html.erb
<%- model_class = Cliente -%>
<div class="page-header">
  <h1>Clientes</h1>

  <table class="table table-hover" >
    <thead>
      <tr>
        <th>Nombres</th>
        <th>Apellidos</th>
        <th>Cedula</th>
        <th>Empresa</th>
        <th>Nit</th>
        <th>Cargo</th>
        <th>Telefono</th>
        <th>Direccion</th>
        <th>Celular</th>
        <th>Fax</th>
        <th>Email</th>
        <th>Ubicacion</th>
      </tr>
    </thead>
    <tbody>
      <%= render @clientes %>
    </tbody>
  </table>

  <tfoot>
    <p><%= link_to "Nuevo Cliente", new_cliente_path, :remote => true, :class => 'btn btn-small btn-success' %></p>
  </tfoot>
</div>

app/views/clientes/new.js.erb
$.lazybox("<%= escape_javascript(render :partial => 'form') %>");
$('#lazybox').css({margin: '50px'});

app/views/clientes/show.js.erb
$.lazybox("<%= j(render 'show') %>", {closeImg: true, klass: 'sticker', fixed: true});

app/views/clientes/update.js.erb
$('tr#cliente_<%= @cliente.id %>').replaceWith("<%= escape_javascript(render @cliente) %>")
$.lazybox.close()