config/routes.rb
FEDCIM::Application.routes.draw do

  get 'cotizaciones/update_detalle', to: 'cotizaciones#update_detalle'
  
  resources :detalles

  resources :servicios

  get "stats" => "stats#index", :as => "stats"

  resources :documentos

  resources :municipios do
    get :autocomplete_departamento_nombre, :on => :collection
  end 

  resources :departamentos

  get "logout" => "sessions#destroy", :as => "logout"
  get "login"  => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get "pages/home"

  get 'cotizaciones/cal_cost', to: 'cotizaciones#cal_cost'
  get 'cotizaciones/cal_costp', to: 'cotizaciones#cal_costp'
  get 'cotizaciones/total_cost', to: 'cotizaciones#total_cost'

  resources :users

  resources :sessions

  resources :cotizaciones

  resources :patronajes_basicos
  resources :clientes do 
    get :autocomplete_municipio_nombre, :on => :collection  
  end
  
  resources :contactos

  root :to => 'pages#home'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new # guest user(not logged in)
    if user.has_role? :admin
        can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  belongs_to :municipio
  attr_accessible :nombres, :apellidos, :cedula, :empresa, :nit
  attr_accessible :cargo, :telefono, :direccion, :celular, :fax, :email, :municipio_id
  attr_accessible :municipio_nombre

  def municipio_nombre
    municipio.nombre if municipio
  end

  def municipio_nombre=(nombre)
  	self.municipio  = Municipio.find_or_create_by_nombre(nombre) unless nombre.blank? 
  end

end

app/models/contacto.rb
class Contacto < ActiveRecord::Base
  attr_accessible :apellido, :celular, :email, :nombre, :telefono, :created_at, :mes

    def self.splfecm(fecha)
	    fecstr = fecha.to_s 
	  	splife = fecstr.split("-")
	  	@fec = splife[1]
	  	@fec.to_i
	end

	def self.splfecd(fecha)
	    fecstr = fecha.to_s 
	  	splife = fecstr.split("-")
	  	@fec = splife[2]
	  	@fec.to_i
	end

	def self.splfeca(fecha)
	    fecstr = fecha.to_s 
	  	splife = fecstr.split("-")
	  	@fec = splife[0]
	  	@fec.to_i
	end

end

app/models/cotizacion.rb
class Cotizacion < ActiveRecord::Base
  belongs_to :servicio
  belongs_to :detalle
  attr_accessible :precio, :total, :servicio_id, :detalle_id
end

app/models/departamento.rb
class Departamento < ActiveRecord::Base
  has_many :municipios
  attr_accessible :nombre, :sigla
end

app/models/detalle.rb
class Detalle < ActiveRecord::Base
  belongs_to :servicio
  attr_accessible :pieza, :precio, :servicio_id
end

app/models/documento.rb
class Documento < ActiveRecord::Base
  # attr_accessible :title, :body
  #paperclip
  attr_accessible :precios
  has_attached_file :precios,
  :url  => "/assets/documentos/:id/:style/:basename.:extension",
  :path => ":rails_root/public/assets/documentos/:id/:style/:basename.:extension"

  validates_attachment_presence :precios
  #validates_attachment_size :foto, :less_than => 5.megabytes
  validates_attachment_content_type :precios, :content_type => ['application/pdf'],
  :message => "solo se permiten pdf"
end

app/models/municipio.rb
class Municipio < ActiveRecord::Base
  belongs_to :departamento
  attr_accessible :nombre, :sigla, :departamento_id, :departamento_nombre

  def departamento_nombre
  	departamento.nombre if departamento
  end

  def departamento_nombre=(nombre)
  	self.departamento  = Departamento.find_or_create_by_nombre(nombre) unless nombre.blank? 
  end

  def self.muni_ubica(muni)
  	@ubica = muni.nombre + ' | ' + muni.departamento.nombre
  end

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify

  #has_and_belongs_to_many :users
  #belongs_to :resource, :polymorphic => true

  def self.act
  		role = Role.all
  end
end

app/models/servicio.rb
class Servicio < ActiveRecord::Base
  has_many :cotizaciones
  has_many :detalles	
  attr_accessible :nombre
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  authenticates_with_sorcery!
  attr_accessible :username,:email, :password, :salt 
  attr_accessible :password_confirmation
  attr_accessible :created_at, :updated_at, :remember_me_token, :remember_me_token_expires_at 


  validates_presence_of :password_confirmation
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  validates_presence_of :username
  validates_uniqueness_of :username
end
  

app/controllers/municipios_controller.rb
class MunicipiosController < ApplicationController
  load_and_authorize_resource :only => [:new, :edit, :destroy]
  autocomplete :departamento, :nombre, :full => true
  
  def index
    @municipios = Municipio.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @municipios }
    end
  end

  def show
    @municipio = Municipio.find(params[:id])
  end

  def new
    @municipio = Municipio.new
  end

  def edit
    @municipio = Municipio.find(params[:id])
  end

  def create
    @municipio = Municipio.new(params[:municipio])
    @municipio.nombre = Municipio.muni_ubica(@municipio)
    render :action => :new unless @municipio.save
  end

  def update
    @municipio = Municipio.find(params[:id])
    @municipio.nombre = Municipio.muni_ubica(@municipio)
    render :action => :edit unless @municipio.update_attributes(params[:municipio])
  end

  def destroy
    @municipio = Municipio.find(params[:id])
    @municipio.destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/contactos_helper.rb
module ContactosHelper
end

app/helpers/detalles_helper.rb
module DetallesHelper
end

app/helpers/documentos_helper.rb
module DocumentosHelper
end

app/helpers/municipios_helper.rb
module MunicipiosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/servicios_helper.rb
module ServiciosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stats_helper.rb
 module StatsHelper
 
	def stat_for_contactos
		@numcon = Contacto.count(:group => :mes)

		leyenda = []         # leyendas del grafico

		@numcon.collect do |key, value| 
			case key
			when 1
			  leyenda << "Enero #{value} Contactos"
			when 2
			  leyenda << "Febrero #{value} Contactos"
			when 3
			  leyenda << "Marzo #{value} Contactos"
			when 4
			  leyenda << "Abril  #{value} Contactos"
			when 5
			  leyenda << "Mayo #{value} Contactos"
			when 6
			  leyenda << "Junio #{value} Contactos"
			when 7
			  leyenda << "Julio #{value} Contactos"
			when 8
			  leyenda << "Agosto #{value} Contactos"
		    when 9
			  leyenda << "Septiembre #{value} Contactos"
			when 10
			  leyenda << "Octubre #{value} Contactos"
			when 11
			  leyenda << "Noviembre #{value} Contactos"
			when 12
			  leyenda << "Diciembre #{value} Contactos"
			when nil
			  leyenda << "No Hay Valoracion"
			end
		end

		Gchart.pie(
	    :size => '695x380',
	    :theme => :keynote,
	    :title => "Contactos por Mes", 
	    :bg => 'efefef',
	    :labels => leyenda,
	    :data => @numcon.values,
	    :axis_with_labels => 'x,y',
	    :axis_labels =>  [@numcon.values])
	    
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/municipios/_form.html.erb
<%= simple_form_for(@municipio, :html => { :class => 'form-horizontal' }, :remote => true) do |f| %>

  <%= f.input :nombre, :label => "Nombre", :require => true  %>
  <%= f.input :sigla, :label => "Sigla", :require => true  %>
  <%= f.input :departamento_nombre, :url => autocomplete_departamento_nombre_municipios_path, :as => :autocomplete, :id_element => '#id'%>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn btn-primary btn-small' %>
    <%= link_to "Atras", municipios_path, :class => 'btn btn-small btn-info' %>
  </div>
<% end %>

app/views/municipios/_municipio.html.erb
<tr id=<%= "municipio_#{municipio.id}"%>>
     
    <td><%= municipio.id %></td>
	<td><%= municipio.nombre %></td>
	<td><%= municipio.sigla%></td>
	<td>
		<%= link_to 'Mostrar', municipio, :remote => true, :class => 'btn btn-mini'%>
		<%= link_to 'Editar',edit_municipio_path(municipio), :remote => true, :class => 'btn btn-mini'%>
		<%= link_to 'Eliminar', municipio, :data => {:confirm => 'Esta Seguro??'}, :method => :delete,:remote => true, :class => 'btn btn-mini btn-danger'%>
	</td>
</tr>

app/views/municipios/_show.html.erb
<%- model_class = Municipio -%>
<div class="page-header">
  <h1>Municipios</h1>
</div>

<div class="municipio">
  <p><%= @municipio.nombre%></p>
  <p><%= @municipio.sigla%></p>
</div>

app/views/municipios/create.js.erb
$('table tbody').append("<%= escape_javascript(render @municipio )%>")
$.lazybox.close()

app/views/municipios/destroy.js.erb
$("table tr#municipio_<%= @municipio.id %>").remove()

app/views/municipios/edit.js.erb
$.lazybox("<%= j(render :partial => 'form')%>",{niceClose: true})

app/views/municipios/index.html.erb
<%- model_class = Municipio -%>
<div class="page-header">
  <div class="page-header">
    <h1>Municipios</h1>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>id</th>
        <th>Nombre</th>
        <th>Sigla</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      <%= render @municipios %>
    </tbody>
  </table>
  <tfoot>
    <%= link_to "Nuevo Munnicipio", new_municipio_path, :remote => true, :class => 'btn btn-primary' %>
  </tfoot>
</div>

app/views/municipios/new.js.erb
$.lazybox("<%= escape_javascript(render :partial => 'form' )%>")

app/views/municipios/show.js.erb
$.lazybox("<%= j(render 'show')%>", {niceClose :true, klas: 'sticker',  fixed: true})

app/views/municipios/update.js.erb
$('tr#municipio_<%= @municipio.id %>').replaceWith("<%= escape_javascript(render @municipio)%>")
$.lazybox.close()