config/routes.rb
FEDCIM::Application.routes.draw do

  get 'cotizaciones/update_detalle', to: 'cotizaciones#update_detalle'
  
  resources :detalles

  resources :servicios

  get "stats" => "stats#index", :as => "stats"

  resources :documentos

  resources :municipios do
    get :autocomplete_departamento_nombre, :on => :collection
  end 

  resources :departamentos

  get "logout" => "sessions#destroy", :as => "logout"
  get "login"  => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get "pages/home"

  get 'cotizaciones/cal_cost', to: 'cotizaciones#cal_cost'
  get 'cotizaciones/cal_costp', to: 'cotizaciones#cal_costp'
  get 'cotizaciones/total_cost', to: 'cotizaciones#total_cost'

  resources :users

  resources :sessions

  resources :cotizaciones

  resources :patronajes_basicos
  resources :clientes do 
    get :autocomplete_municipio_nombre, :on => :collection  
  end
  
  resources :contactos

  root :to => 'pages#home'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new # guest user(not logged in)
    if user.has_role? :admin
        can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  belongs_to :municipio
  attr_accessible :nombres, :apellidos, :cedula, :empresa, :nit
  attr_accessible :cargo, :telefono, :direccion, :celular, :fax, :email, :municipio_id
  attr_accessible :municipio_nombre

  def municipio_nombre
    municipio.nombre if municipio
  end

  def municipio_nombre=(nombre)
  	self.municipio  = Municipio.find_or_create_by_nombre(nombre) unless nombre.blank? 
  end

end

app/models/contacto.rb
class Contacto < ActiveRecord::Base
  attr_accessible :apellido, :celular, :email, :nombre, :telefono, :created_at, :mes

    def self.splfecm(fecha)
	    fecstr = fecha.to_s 
	  	splife = fecstr.split("-")
	  	@fec = splife[1]
	  	@fec.to_i
	end

	def self.splfecd(fecha)
	    fecstr = fecha.to_s 
	  	splife = fecstr.split("-")
	  	@fec = splife[2]
	  	@fec.to_i
	end

	def self.splfeca(fecha)
	    fecstr = fecha.to_s 
	  	splife = fecstr.split("-")
	  	@fec = splife[0]
	  	@fec.to_i
	end

end

app/models/cotizacion.rb
class Cotizacion < ActiveRecord::Base
  belongs_to :servicio
  belongs_to :detalle
  attr_accessible :precio, :total, :servicio_id, :detalle_id
end

app/models/departamento.rb
class Departamento < ActiveRecord::Base
  has_many :municipios
  attr_accessible :nombre, :sigla
end

app/models/detalle.rb
class Detalle < ActiveRecord::Base
  belongs_to :servicio
  attr_accessible :pieza, :precio, :servicio_id
end

app/models/documento.rb
class Documento < ActiveRecord::Base
  # attr_accessible :title, :body
  #paperclip
  attr_accessible :precios
  has_attached_file :precios,
  :url  => "/assets/documentos/:id/:style/:basename.:extension",
  :path => ":rails_root/public/assets/documentos/:id/:style/:basename.:extension"

  validates_attachment_presence :precios
  #validates_attachment_size :foto, :less_than => 5.megabytes
  validates_attachment_content_type :precios, :content_type => ['application/pdf'],
  :message => "solo se permiten pdf"
end

app/models/municipio.rb
class Municipio < ActiveRecord::Base
  belongs_to :departamento
  attr_accessible :nombre, :sigla, :departamento_id, :departamento_nombre

  def departamento_nombre
  	departamento.nombre if departamento
  end

  def departamento_nombre=(nombre)
  	self.departamento  = Departamento.find_or_create_by_nombre(nombre) unless nombre.blank? 
  end

  def self.muni_ubica(muni)
  	@ubica = muni.nombre + ' | ' + muni.departamento.nombre
  end

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify

  #has_and_belongs_to_many :users
  #belongs_to :resource, :polymorphic => true

  def self.act
  		role = Role.all
  end
end

app/models/servicio.rb
class Servicio < ActiveRecord::Base
  has_many :cotizaciones
  has_many :detalles	
  attr_accessible :nombre
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  authenticates_with_sorcery!
  attr_accessible :username,:email, :password, :salt 
  attr_accessible :password_confirmation
  attr_accessible :created_at, :updated_at, :remember_me_token, :remember_me_token_expires_at 


  validates_presence_of :password_confirmation
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  validates_presence_of :username
  validates_uniqueness_of :username
end
  

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/contactos_helper.rb
module ContactosHelper
end

app/helpers/detalles_helper.rb
module DetallesHelper
end

app/helpers/documentos_helper.rb
module DocumentosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/servicios_helper.rb
module ServiciosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stats_helper.rb
 module StatsHelper
 
	def stat_for_contactos
		@numcon = Contacto.count(:group => :mes)

		leyenda = []         # leyendas del grafico

		@numcon.collect do |key, value| 
			case key
			when 1
			  leyenda << "Enero #{value} Contactos"
			when 2
			  leyenda << "Febrero #{value} Contactos"
			when 3
			  leyenda << "Marzo #{value} Contactos"
			when 4
			  leyenda << "Abril  #{value} Contactos"
			when 5
			  leyenda << "Mayo #{value} Contactos"
			when 6
			  leyenda << "Junio #{value} Contactos"
			when 7
			  leyenda << "Julio #{value} Contactos"
			when 8
			  leyenda << "Agosto #{value} Contactos"
		    when 9
			  leyenda << "Septiembre #{value} Contactos"
			when 10
			  leyenda << "Octubre #{value} Contactos"
			when 11
			  leyenda << "Noviembre #{value} Contactos"
			when 12
			  leyenda << "Diciembre #{value} Contactos"
			when nil
			  leyenda << "No Hay Valoracion"
			end
		end

		Gchart.pie(
	    :size => '695x380',
	    :theme => :keynote,
	    :title => "Contactos por Mes", 
	    :bg => 'efefef',
	    :labels => leyenda,
	    :data => @numcon.values,
	    :axis_with_labels => 'x,y',
	    :axis_labels =>  [@numcon.values])
	    
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/escalados_tallas/edit.html.erb
<%- model_class = EscaladoTalla -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/escalados_tallas/index.html.erb
<%- model_class = EscaladoTalla -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:pieza) %></th>
      <th><%= model_class.human_attribute_name(:precio) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @escalados_tallas.each do |escalado_talla| %>
      <tr>
        <td><%= link_to escalado_talla.id, escalado_talla_path(escalado_talla) %></td>
        <td><%= escalado_talla.pieza %></td>
        <td><%= escalado_talla.precio %></td>
        <td><%=l escalado_talla.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_escalado_talla_path(escalado_talla), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      escalado_talla_path(escalado_talla),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_escalado_talla_path,
            :class => 'btn btn-primary' %>

app/views/escalados_tallas/new.html.erb
<%- model_class = EscaladoTalla -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/escalados_tallas/show.html.erb
<%- model_class = EscaladoTalla -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:pieza) %>:</strong></dt>
  <dd><%= @escalado_talla.pieza %></dd>
  <dt><strong><%= model_class.human_attribute_name(:precio) %>:</strong></dt>
  <dd><%= @escalado_talla.precio %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              escalados_tallas_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_escalado_talla_path(@escalado_talla), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              escalado_talla_path(@escalado_talla),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/_footer.html.erb
<ul>
    <p>SENA 2013 - Centro de Formacion en Diseño, Confeccion y Moda Calatraba. All rights reserved Christiam Camilo Gomez Gañan. kyubi_589@hotmail.com</p>
</ul>

app/views/layouts/_navigation.html.erb
<ul class="nav nav-pills">

	<li>
		<p>SENA FEDCIM
		<%= image_tag("Sena-Virtual.png", :class => 'img-circle') %></p>
	</li>

    <li class="divider-vertical"></li>

	<li class="active">
		<%= link_to('Home', root_path) %>
	</li>


	<li>
		<%= link_to 'contactenos', new_contacto_path, :remote => true %> 
	</li>


	<% if current_user %>

	    <li>
			<%= link_to 'clientes', clientes_path %> 
		</li>

		<li> 
			<%= link_to 'Documentos', documentos_path %>  
		</li>
	<% else %>	

		<li>
		   <%= link_to "ingresar", login_path %>
	    </li>

	    
	<% end %>  

	<li class="divider-vertical"></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <link rel="shortcut icon" href="assets/logofedcimm.png"/>
	    <title>FEDCIM</title>
	    <%= stylesheet_link_tag "application", :media => "all" %>
	    <%= javascript_include_tag "application" %>
	    <%= csrf_meta_tags %>
    </head>
    <div class="container">
        <body>
            <div>
                <header  class="navbar navbar-fixed-top">
                    <nav class="navbar-inner">
                        <div class="container">
                            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                              <span class="icon-bar"></span>
                              <span class="icon-bar"></span>
                              <span class="icon-bar"></span>
                            </a>
                            <div class="nav-collapse">
                             <%= render 'layouts/navigation' %>
                            </div> 
                            <% if current_user %>
                                <div class="btn-group btuser">
                                    <a class="btn btn-success dropdown-toggle" data-toggle="dropdown" href="#"><i class="  icon-user icon-white "></i> User:<%= current_user.username %></a>
                                    <ul class="dropdown-menu span1">
                                        <li>
                                            <%= link_to(logout_path) do %>
                                               salir <i class=" icon-lock"></i>
                                            <% end %>
                                        </li>
                                        <li>
                                            <%= link_to(users_path) do %>
                                               Usuarios <i class=" icon-wrench"></i>
                                            <% end %>
                                        </li>
                                        <li>
                                            <%= link_to(departamentos_path) do %>
                                            Departamentos<i class=" icon-wrench"></i>
                                            <% end %>
                                        </li>
                                        <li>
                                            <%= link_to(municipios_path) do %>
                                            Municipios<i class=" icon-wrench"></i>
                                            <% end %>
                                        </li>
                                        <li>
                                            <%= link_to(stats_path) do %>
                                               Estadisticas <i class=" icon-wrench"></i>
                                            <% end %>
                                        </li>
                                        <li class="divider"></li>
                                        <li>
                                            <%= link_to(contactos_path) do %>
                                            Contactos <i class=" icon-wrench"></i>
                                            <% end %>
                                        </li>
                                    </ul>
                                </div>    
                            <% end %>
                        </div> 
                    </nav>
                </header>  
    	        <%- flash.each do |name, msg| -%>
    	        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    	        <%- end -%> 
            </div>
            <div class="responsive" >
                <%= yield %>
            </div>
            <br/>
            <div id="foot">
    		   <%= render 'layouts/footer' %>
    		</div>
        </body>
    </div>
</html>

app/views/pages/home.html.erb
<div class="responsive" id="container" >
    <div>
        <h1>FEDCIM</h1>
        <p>FEDCIM  es creada para el centro  Diseño de la aplicacion para el Centro de Formacion en Diseño, Confeccion y Moda SENA.Su fin es dar una manera de vender los servicios que brinda con  la maquina  miilan </p>
    </div>
    <div id="myModal1" class="modal hide fade  " tabindex="-1" role="dialog" aria-labelledby=" myModalLabel" aria-hidden="true">
        
        <div  class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h5 id="myModalLabel">Servicios</h5>
        </div>

        <div class="modal-body" id="imgenmod1">
            <div class="control-group">
                <div class="row">
                    <div class="span4">
                        <p><strong id="somp">Diseño de colecciones</strong></p>
                        <p><strong id="somp">Dijitalizacion de Moldes</strong></p>
                        <p><strong id="somp">Elaboracion de Molderia: Molde patrón</p>
                        <p><strong id="somp">Elaboración de Molderia: Escalado</strong></p>
                        <p><strong id="somp">Elaboracion de Ficha Técnica</strong></p>
                    </div>
                    <div class="span2">
                        <div class="row">
                            <p><strong id="somp">Elaboración de trazos sistematizados</strong></p>
                            <p><strong id="somp">Plotteo de Trazos</strong></p>
                            <p><strong id="somp">Corte de Prendas</strong></p>
                            <p><strong id="somp">Tiqueteado</strong></p>
                        </div>
                    </div>    
                </div>    
                <div class="modal-footer">
                   <button class="btn btn-mini" data-dismiss="modal" aria- hidden="true">Cerrar</button>
                </div>

            </div>
        </div>
    </div>

    <!--fin modal uno-->
    <div id="myModal2" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby=" myModalLabel" aria-hidden="true">
        <div  class="modal-header">
            <h5 id="myModalLabel">Maquina Milan:</h5>
        </div>

        <div class="modal-body">
            <p>Durante cuatro años Inexmoda lideró el reto de fortalecer la competitividad del sector textil a través de la ejecución del proyecto "Plataforma de Innovación para el sector Textil-Confección", financiado por el Banco Interamericano de Desarrollo a través del FOMIN. </p>
            <p>En el marco de este proyecto, la Alcaldia de Milán donó una máquina cortadora de tela con el fin de prestar un servicio de alta tecnologia en el SENA - Sede Calatrava, Itagüi el 28 de diciembre de 2010. A raíz de esta donaciónnación, nació una alianza interinstitucional, con Confama, Interactuar, Cámara de Comercio de Medellin para Antioquia, Sena e Inexmoda, con el fin de proporcionar la prestación de servicios de la máquina; este convenio finalizó en junio de 2012. </p>
        </div> 

        <div class="modal-footer">
            <button class="btn btn-mini" data-dismiss="modal" aria-hidden="true">Cerrar</button>
        </div>
    </div>

    <div id="myModal3" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby=" myModalLabel" aria-hidden="true">
        <div  class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
           <h5 id="myModalLabel">Maquina Milan:</h5>
        </div>
        <div class="resposive">
            <div class="modal-body">
                <p>Corte perfecto: para que una prenda sea de valor agregado, el corte debe ser perfecto. La máquina nos permitirá tecnificar el proceso de corte. </p>
                <p> Ahorro en tiempo gracias a la posibilidad de cortar diferentes cantidades de piezas en simultánea (puños, cuellos, mangas, etc.).</p>
                <p>Mínimo desperdicio: actuar sobre los puntos más débiles en la fase de producción, permitirá a los productores estimar los costos de producción desde el desarrollo de productos, realizando considerables ahorros de material. La tela es elemento más costoso y el factor productivo de mayor relevancia. Este representa generalmente el 50% del costo total del producto.</p>
                <p>Sistema automático para extender la tela.
                    Software compatible con otros programas de diseño que favorecerá no sólo el proceso de corte sino de diseño y patronaje (tecnificación).</p>
                    
            </div> 
        </div>
        <div class="modal-footer">
            <button class="btn btn-mini" data-dismiss="modal" aria-hidden="true">Cerrar</button>
        </div>
    </div>

    <div id="mod">
        <p class="muted pull-right"><a  href="#myModal3"  role="button" class="pull-right btn btn-success btn-small " data-toggle="modal" title="Ver Informacion">Beneficios</a></p>
       
        <p class="muted pull-right"><a  href="#myModal2"  role="button" class="pull-right btn btn-success btn-small" data-toggle="modal" title="Ver Informacion">Proyecto</a></p>

        <p class="muted pull-right"><a  href="#myModal1"  role="button" class="pull-right btn btn-success btn-small" data-toggle="modal" title="Ver Informacion">Servicios de Diseño y Molderia</a></p>


 <div class="btn-group btuser" id="mod">
   <a class="btn btn-success dropdown-toggle" data-toggle="dropdown" href="#"><i class="   icon-file icon-white "></i>  Documentos</a>
<ul class="dropdown-menu">                          

        <% @documentos.each do |documento| %>
             
        <li><%= link_to "#{documento.precios_file_name}", documento.precios.url, :class => 'btn btn-info btn-small' %></li>
					
                                            
    
                                        
                                 
                             
        <% end %>
</ul>
   </div> 
    </div>
</div>    
   